### ISSUE TITLE
SEO Fundamentals

### ISSUE THREAD

**Issue by tobyhunt** [pebblecode/pebblecode.com#84]
- [x] Google sitemap file (see #67)
- [x] robots.txt (#74)
- [x] Submit to search engines
- [x] Validate HTML
- [x] ~~Validate CSS~~ (We looked at CSS lint and it is not really useful to us.)
- [x] Compress CSS (#88)
- [x] Compress JavaScript (#88)
- [ ] Run through YSlow
- [ ] Run through Google PageSpeed: [pebblecode.com result](https://developers.google.com/speed/pagespeed/insights#url=www.pebblecode.com&mobile=false)
- [x] Gzip site (#88)
- [ ] Use browser cache (#88)
- [x] People page optimization (#99)

others? 
## Resources
- [Ruby w3c_validators](https://github.com/alexdunae/w3c_validators)
- [Rack::Deflater](http://artsy.github.io/blog/2012/02/24/10x-rack-and-rails-output-compression-with-rack-deflater/)
- http://stackoverflow.com/questions/15190295/how-to-enable-gzip-compression-for-static-rack-sites-on-heroku-cedar
